debug: true
image_topic: /camera/rgb/image_raw
enable_tf: false
marker_dictionary: 11
markers_length: [150] # length in mm.
markers_150: [1, 2, 3, 4, 5, 6, 7, 8] # Markers id with length 0.
markerTF_name: id_
camera_matrix: [530.4669406576809, 0.0, 320.5, 0.0, 530.4669406576809, 240.5, 0.0, 0.0, 1.0]
camera_distortion: [0.0, 0.0, 0.0, 0.0, 0.0]
static_variance: false
static_camera_transform: true
mapTF_name: world
baseTF_name: base_footprint
markerTF_name: panelTF/aruco_6x6_
cameraTF_name: camera_rgb_optical_frame
poseTopic_name: pose
variance_matrix: [0.01, 0, 0, 0, 0, 0, 
                  0, 0.01, 0, 0, 0, 0,
                  0, 0, 0.01, 0, 0, 0,
                  0, 0, 0, 0.01, 0, 0,
                  0, 0, 0, 0, 0.01, 0,
                  0, 0, 0, 0, 0, 0.01]